spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/newvacc?useUnicode=true&characterEncoding=utf-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    suffix: .ftl     #设置后缀
    template-loader-path: classpath:/templates/  #设置加载模板文件路径位置  默认位置
  devtools:
    restart:
      enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
server:
  port: 8080
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl